"""initial creatorops schema

Revision ID: 8012c4276b8b
Revises:
Create Date: 2026-09-11 23:34:26.377885
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8012c4276b8b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("slug", name=op.f("uq_brands_slug")),
    )
    op.create_table(
        "inbox_messages",
        sa.Column("consumer", sa.String(length=120), nullable=False),
        sa.Column("message_id", sa.String(length=240), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_messages")),
        sa.UniqueConstraint("consumer", "message_id", name="uq_inbox_consumer_message"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_unpublished", "outbox_events", ["published_at", "created_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "staff", "creator", name="user_kind", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_audit_logs_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_entity", "audit_logs", ["brand_id", "entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "brand_memberships",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "ops",
                "finance",
                name="brand_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_brand_memberships_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_brand_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_memberships")),
        sa.UniqueConstraint("brand_id", "user_id", name="uq_brand_membership_brand_user"),
    )
    op.create_index("ix_brand_memberships_user", "brand_memberships", ["user_id"], unique=False)
    op.create_table(
        "programs",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "paused",
                "closed",
                name="program_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attribution_window_days", sa.Integer(), nullable=False),
        sa.Column("return_window_days", sa.Integer(), nullable=False),
        sa.Column("payout_minimum", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_programs_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
        sa.UniqueConstraint("brand_id", "slug", name="uq_program_brand_slug"),
    )
    op.create_index(op.f("ix_programs_brand_id"), "programs", ["brand_id"], unique=False)
    op.create_table(
        "reconciliation_runs",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("started_by", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="reconciliation_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_reconciliation_runs_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
            name=op.f("fk_reconciliation_runs_started_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_runs")),
    )
    op.create_index(
        op.f("ix_reconciliation_runs_brand_id"), "reconciliation_runs", ["brand_id"], unique=False
    )
    op.create_table(
        "social_profiles",
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "network",
            sa.Enum(
                "instagram",
                "tiktok",
                name="social_network",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("handle", sa.String(length=120), nullable=False),
        sa.Column("handle_normalized", sa.String(length=120), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_social_profiles_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_profiles")),
        sa.UniqueConstraint("creator_id", "network", name="uq_creator_social_network"),
        sa.UniqueConstraint("network", "handle_normalized", name="uq_social_network_handle"),
    )
    op.create_table(
        "campaigns",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "scheduled",
                "active",
                "ended",
                "cancelled",
                name="campaign_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("briefing", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_campaigns_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("program_id", "name", name="uq_campaign_program_name"),
    )
    op.create_index(op.f("ix_campaigns_program_id"), "campaigns", ["program_id"], unique=False)
    op.create_table(
        "creator_applications",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "self",
                "invite",
                name="application_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "in_review",
                "approved",
                "rejected",
                "withdrawn",
                name="application_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("motivation", sa.Text(), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_creator_applications_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_creator_applications_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_creator_applications_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creator_applications")),
        sa.UniqueConstraint("program_id", "creator_id", name="uq_application_program_creator"),
    )
    op.create_index(
        "ix_application_program_status",
        "creator_applications",
        ["program_id", "status"],
        unique=False,
    )
    op.create_table(
        "creator_invitations",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "expired",
                "revoked",
                name="invitation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_creator_invitations_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creator_invitations")),
        sa.UniqueConstraint("token_hash", name="uq_invitation_token_hash"),
    )
    op.create_index(
        op.f("ix_creator_invitations_program_id"),
        "creator_invitations",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "paid",
                "cancelled",
                "partially_refunded",
                "refunded",
                name="order_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("gross_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("refunded_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_orders_brand_id_brands"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_orders_program_id_programs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("brand_id", "external_id", name="uq_order_brand_external"),
    )
    op.create_index("ix_orders_brand_status", "orders", ["brand_id", "status"], unique=False)
    op.create_index(op.f("ix_orders_program_id"), "orders", ["program_id"], unique=False)
    op.create_table(
        "payout_batches",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "processing",
                "completed",
                "partially_failed",
                "cancelled",
                name="payout_batch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approval_comment", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_payout_batches_approved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_payout_batches_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_payout_batches_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_payout_batches_program_id_programs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_batches")),
    )
    op.create_index(
        "ix_payout_batch_program_status", "payout_batches", ["program_id", "status"], unique=False
    )
    op.create_table(
        "program_terms",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_program_terms_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_terms")),
        sa.UniqueConstraint("program_id", "version", name="uq_program_terms_version"),
    )
    op.create_index(
        op.f("ix_program_terms_program_id"), "program_terms", ["program_id"], unique=False
    )
    op.create_table(
        "commerce_webhook_events",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("external_event_id", sa.String(length=160), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "order.created",
                "order.paid",
                "order.cancelled",
                "order.refunded",
                name="commerce_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processed",
                "ignored",
                name="webhook_processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_commerce_webhook_events_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_commerce_webhook_events_order_id_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commerce_webhook_events")),
        sa.UniqueConstraint(
            "brand_id", "provider", "external_event_id", name="uq_webhook_brand_provider_event"
        ),
    )
    op.create_index(
        "ix_webhook_received_at", "commerce_webhook_events", ["received_at"], unique=False
    )
    op.create_table(
        "commission_plans",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("base_rate", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("return_window_days", sa.Integer(), nullable=False),
        sa.Column("payout_minimum", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_commission_plans_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_commission_plans_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_plans")),
        sa.UniqueConstraint(
            "program_id", "campaign_id", "version", name="uq_commission_plan_scope_version"
        ),
    )
    op.create_index(
        "ix_commission_plan_active",
        "commission_plans",
        ["program_id", "campaign_id", "active_from"],
        unique=False,
    )
    op.create_table(
        "program_memberships",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting_terms",
                "active",
                "paused",
                "offboarded",
                name="membership_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["creator_applications.id"],
            name=op.f("fk_program_memberships_application_id_creator_applications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_program_memberships_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_program_memberships_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_memberships")),
        sa.UniqueConstraint("application_id", name=op.f("uq_program_memberships_application_id")),
        sa.UniqueConstraint("program_id", "creator_id", name="uq_membership_program_creator"),
    )
    op.create_index(
        "ix_membership_program_status",
        "program_memberships",
        ["program_id", "status"],
        unique=False,
    )
    op.create_table(
        "affiliate_assets",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "coupon",
                "link",
                name="affiliate_asset_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("target_url", sa.String(length=1000), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_affiliate_assets_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_affiliate_assets_membership_id_program_memberships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_assets")),
        sa.UniqueConstraint("asset_type", "code", name="uq_affiliate_asset_type_code"),
    )
    op.create_index(
        "ix_affiliate_assets_membership",
        "affiliate_assets",
        ["membership_id", "active"],
        unique=False,
    )
    op.create_table(
        "bonus_rules",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "metric",
            sa.Enum(
                "gmv", "orders", name="commission_metric", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("threshold", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["commission_plans.id"],
            name=op.f("fk_bonus_rules_plan_id_commission_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bonus_rules")),
    )
    op.create_index(op.f("ix_bonus_rules_plan_id"), "bonus_rules", ["plan_id"], unique=False)
    op.create_table(
        "commission_tiers",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("threshold_gmv", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("rate", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["commission_plans.id"],
            name=op.f("fk_commission_tiers_plan_id_commission_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_tiers")),
        sa.UniqueConstraint("plan_id", "threshold_gmv", name="uq_commission_tier_threshold"),
    )
    op.create_index(
        op.f("ix_commission_tiers_plan_id"), "commission_tiers", ["plan_id"], unique=False
    )
    op.create_table(
        "content_evidence",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("membership_id", sa.Uuid(), nullable=True),
        sa.Column(
            "network",
            sa.Enum(
                "instagram",
                "tiktok",
                name="content_social_network",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_post_id", sa.String(length=160), nullable=False),
        sa.Column("firestore_path", sa.String(length=500), nullable=False),
        sa.Column("handle_normalized", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "detected",
                "matched",
                "approved",
                "rejected",
                name="content_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_content_evidence_brand_id_brands"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_content_evidence_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_content_evidence_membership_id_program_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_content_evidence_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_content_evidence_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_evidence")),
        sa.UniqueConstraint("network", "external_post_id", name="uq_content_network_external"),
    )
    op.create_index(
        "ix_content_brand_status", "content_evidence", ["brand_id", "status"], unique=False
    )
    op.create_table(
        "payouts",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending",
                "confirmed",
                "failed",
                "unknown",
                name="payout_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("provider_reference", sa.String(length=160), nullable=True),
        sa.Column(
            "simulation_scenario",
            sa.Enum(
                "success",
                "failure",
                "timeout_before",
                "timeout_after",
                name="provider_scenario",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unknown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["payout_batches.id"],
            name=op.f("fk_payouts_batch_id_payout_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_payouts_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_payouts_membership_id_program_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_payouts_program_id_programs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payouts")),
        sa.UniqueConstraint("batch_id", "membership_id", name="uq_payout_batch_membership"),
        sa.UniqueConstraint("idempotency_key", name="uq_payout_idempotency_key"),
        sa.UniqueConstraint("provider_reference", name="uq_payout_provider_reference"),
    )
    op.create_index("ix_payout_brand_status", "payouts", ["brand_id", "status"], unique=False)
    op.create_table(
        "terms_acceptances",
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("terms_id", sa.Uuid(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_terms_acceptances_membership_id_program_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["terms_id"],
            ["program_terms.id"],
            name=op.f("fk_terms_acceptances_terms_id_program_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms_acceptances")),
        sa.UniqueConstraint("membership_id", "terms_id", name="uq_terms_acceptance"),
    )
    op.create_table(
        "affiliate_clicks",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("visitor_id", sa.String(length=120), nullable=False),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["affiliate_assets.id"],
            name=op.f("fk_affiliate_clicks_asset_id_affiliate_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_clicks")),
    )
    op.create_index(
        op.f("ix_affiliate_clicks_asset_id"), "affiliate_clicks", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_affiliate_clicks_visitor_id"), "affiliate_clicks", ["visitor_id"], unique=False
    )
    op.create_table(
        "agent_findings",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("payout_id", sa.Uuid(), nullable=False),
        sa.Column(
            "finding_type",
            sa.Enum(
                "provider_confirmed_internal_unknown",
                "provider_missing_internal_unknown",
                "amount_mismatch",
                "duplicate_provider_transfer",
                "ledger_balance_mismatch",
                name="finding_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "open",
                "proposed",
                "resolved",
                "dismissed",
                name="finding_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("payout_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_agent_findings_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
            name=op.f("fk_agent_findings_payout_id_payouts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
            name=op.f("fk_agent_findings_run_id_reconciliation_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_findings")),
        sa.UniqueConstraint(
            "payout_id", "finding_type", "evidence_hash", name="uq_finding_evidence"
        ),
    )
    op.create_index("ix_finding_brand_state", "agent_findings", ["brand_id", "state"], unique=False)
    op.create_table(
        "commissions",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("bonus_rule_id", sa.Uuid(), nullable=True),
        sa.Column("adjustment_of_id", sa.Uuid(), nullable=True),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "sale",
                "bonus",
                "refund_adjustment",
                name="commission_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "available",
                "reversed",
                name="commission_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("gross_basis", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("rate", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("period_key", sa.String(length=7), nullable=False),
        sa.Column("eligible_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_of_id"],
            ["commissions.id"],
            name=op.f("fk_commissions_adjustment_of_id_commissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bonus_rule_id"],
            ["bonus_rules.id"],
            name=op.f("fk_commissions_bonus_rule_id_bonus_rules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_commissions_membership_id_program_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_commissions_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["commission_plans.id"],
            name=op.f("fk_commissions_plan_id_commission_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["commerce_webhook_events.id"],
            name=op.f("fk_commissions_source_event_id_commerce_webhook_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commissions")),
        sa.UniqueConstraint(
            "membership_id", "bonus_rule_id", "period_key", name="uq_commission_bonus_period"
        ),
        sa.UniqueConstraint(
            "order_id", "kind", "bonus_rule_id", name="uq_commission_order_kind_rule"
        ),
    )
    op.create_index(
        "ix_commission_membership_status", "commissions", ["membership_id", "status"], unique=False
    )
    op.create_index(
        "uq_commission_adjustment_source",
        "commissions",
        ["source_event_id", "adjustment_of_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'refund_adjustment'"),
    )
    op.create_index(
        "uq_commission_sale_order",
        "commissions",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'sale'"),
    )
    op.create_table(
        "agent_proposals",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "confirm_payout",
                "mark_failed_release",
                "compensating_adjustment",
                "manual_review",
                name="proposal_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "draft",
                "gated",
                "blocked",
                "approved",
                "rejected",
                "executed",
                "stale",
                name="proposal_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("risk", sa.String(length=40), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("payout_version", sa.Integer(), nullable=False),
        sa.Column("proposed_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approval_comment", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_comment", sa.Text(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_agent_proposals_approved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["agent_findings.id"],
            name=op.f("fk_agent_proposals_finding_id_agent_findings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by"],
            ["users.id"],
            name=op.f("fk_agent_proposals_rejected_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_proposals")),
    )
    op.create_index(
        "ix_proposal_finding_state", "agent_proposals", ["finding_id", "state"], unique=False
    )
    op.create_table(
        "ledger_entries",
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("commission_id", sa.Uuid(), nullable=True),
        sa.Column("payout_id", sa.Uuid(), nullable=True),
        sa.Column(
            "bucket",
            sa.Enum(
                "pending",
                "available",
                "reserved",
                "paid",
                name="ledger_bucket",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "entry_type",
            sa.Enum(
                "commission_accrued",
                "commission_settled",
                "commission_reversed",
                "payout_reserved",
                "payout_confirmed",
                "payout_released",
                "reconciliation_adjustment",
                name="ledger_entry_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=240), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_ledger_entries_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["commission_id"],
            ["commissions.id"],
            name=op.f("fk_ledger_entries_commission_id_commissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_ledger_entries_membership_id_program_memberships"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["payouts.id"],
            name=op.f("fk_ledger_entries_payout_id_payouts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_ledger_entries_program_id_programs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
        sa.UniqueConstraint("idempotency_key", name="uq_ledger_idempotency_key"),
    )
    op.create_index(
        "ix_ledger_membership_bucket", "ledger_entries", ["membership_id", "bucket"], unique=False
    )
    op.create_index(
        "ix_ledger_program_created", "ledger_entries", ["program_id", "created_at"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION creatorops_reject_ledger_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ledger_entries is append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_entries_no_update_or_delete
        BEFORE UPDATE OR DELETE ON ledger_entries
        FOR EACH ROW EXECUTE FUNCTION creatorops_reject_ledger_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_entries_no_truncate
        BEFORE TRUNCATE ON ledger_entries
        FOR EACH STATEMENT EXECUTE FUNCTION creatorops_reject_ledger_mutation()
        """
    )
    op.create_table(
        "order_attributions",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("coupon_asset_id", sa.Uuid(), nullable=True),
        sa.Column("click_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "coupon",
                "last_click",
                "unattributed",
                "manual",
                name="attribution_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attributed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_order_attributions_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["click_id"],
            ["affiliate_clicks.id"],
            name=op.f("fk_order_attributions_click_id_affiliate_clicks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["coupon_asset_id"],
            ["affiliate_assets.id"],
            name=op.f("fk_order_attributions_coupon_asset_id_affiliate_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["program_memberships.id"],
            name=op.f("fk_order_attributions_membership_id_program_memberships"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_attributions_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_attributions")),
        sa.UniqueConstraint("order_id", name=op.f("uq_order_attributions_order_id")),
    )
    op.create_index(
        op.f("ix_order_attributions_membership_id"),
        "order_attributions",
        ["membership_id"],
        unique=False,
    )
    op.create_table(
        "agent_gate_runs",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "passed", "failed", name="gate_result", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["agent_proposals.id"],
            name=op.f("fk_agent_gate_runs_proposal_id_agent_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_gate_runs")),
    )
    op.create_index(
        op.f("ix_agent_gate_runs_proposal_id"), "agent_gate_runs", ["proposal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_gate_runs_proposal_id"), table_name="agent_gate_runs")
    op.drop_table("agent_gate_runs")
    op.drop_index(op.f("ix_order_attributions_membership_id"), table_name="order_attributions")
    op.drop_table("order_attributions")
    op.execute("DROP TRIGGER ledger_entries_no_truncate ON ledger_entries")
    op.execute("DROP TRIGGER ledger_entries_no_update_or_delete ON ledger_entries")
    op.execute("DROP FUNCTION creatorops_reject_ledger_mutation()")
    op.drop_index("ix_ledger_program_created", table_name="ledger_entries")
    op.drop_index("ix_ledger_membership_bucket", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index("ix_proposal_finding_state", table_name="agent_proposals")
    op.drop_table("agent_proposals")
    op.drop_index(
        "uq_commission_sale_order",
        table_name="commissions",
        postgresql_where=sa.text("kind = 'sale'"),
    )
    op.drop_index(
        "uq_commission_adjustment_source",
        table_name="commissions",
        postgresql_where=sa.text("kind = 'refund_adjustment'"),
    )
    op.drop_index("ix_commission_membership_status", table_name="commissions")
    op.drop_table("commissions")
    op.drop_index("ix_finding_brand_state", table_name="agent_findings")
    op.drop_table("agent_findings")
    op.drop_index(op.f("ix_affiliate_clicks_visitor_id"), table_name="affiliate_clicks")
    op.drop_index(op.f("ix_affiliate_clicks_asset_id"), table_name="affiliate_clicks")
    op.drop_table("affiliate_clicks")
    op.drop_table("terms_acceptances")
    op.drop_index("ix_payout_brand_status", table_name="payouts")
    op.drop_table("payouts")
    op.drop_index("ix_content_brand_status", table_name="content_evidence")
    op.drop_table("content_evidence")
    op.drop_index(op.f("ix_commission_tiers_plan_id"), table_name="commission_tiers")
    op.drop_table("commission_tiers")
    op.drop_index(op.f("ix_bonus_rules_plan_id"), table_name="bonus_rules")
    op.drop_table("bonus_rules")
    op.drop_index("ix_affiliate_assets_membership", table_name="affiliate_assets")
    op.drop_table("affiliate_assets")
    op.drop_index("ix_membership_program_status", table_name="program_memberships")
    op.drop_table("program_memberships")
    op.drop_index("ix_commission_plan_active", table_name="commission_plans")
    op.drop_table("commission_plans")
    op.drop_index("ix_webhook_received_at", table_name="commerce_webhook_events")
    op.drop_table("commerce_webhook_events")
    op.drop_index(op.f("ix_program_terms_program_id"), table_name="program_terms")
    op.drop_table("program_terms")
    op.drop_index("ix_payout_batch_program_status", table_name="payout_batches")
    op.drop_table("payout_batches")
    op.drop_index(op.f("ix_orders_program_id"), table_name="orders")
    op.drop_index("ix_orders_brand_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_creator_invitations_program_id"), table_name="creator_invitations")
    op.drop_table("creator_invitations")
    op.drop_index("ix_application_program_status", table_name="creator_applications")
    op.drop_table("creator_applications")
    op.drop_index(op.f("ix_campaigns_program_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("social_profiles")
    op.drop_index(op.f("ix_reconciliation_runs_brand_id"), table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    op.drop_index(op.f("ix_programs_brand_id"), table_name="programs")
    op.drop_table("programs")
    op.drop_index("ix_brand_memberships_user", table_name="brand_memberships")
    op.drop_table("brand_memberships")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index("ix_outbox_unpublished", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("inbox_messages")
    op.drop_table("brands")
    # ### end Alembic commands ###
