export function money(value: string, currency = 'BRL') {
  if (!/^-?\d+(\.\d+)?$/.test(value)) return value;
  const [integer, fraction = ''] = value.split('.');
  const sign = integer.startsWith('-') ? '−' : '';
  const digits = integer.replace('-', '').replace(/\B(?=(\d{3})+(?!\d))/g, '.');
  return `${sign}${currency === 'BRL' ? 'R$' : currency} ${digits},${fraction.padEnd(2, '0')}`;
}
export const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
export function date(value: string) {
  const dt = new Date(value);
  return Number.isNaN(dt.getTime())
    ? value
    : new Intl.DateTimeFormat('pt-BR', {
        dateStyle: 'short',
        timeStyle: 'short',
        timeZone: timezone,
      }).format(dt);
}
export const labels: Record<string, string> = {
  id: 'Identificador',
  name: 'Nome',
  status: 'Estado',
  state: 'Estado',
  created_at: 'Criado em',
  program_id: 'Programa',
  program_name: 'Programa',
  campaign_id: 'Campanha',
  membership_id: 'Parceria',
  creator_id: 'Creator',
  display_name: 'Nome',
  email: 'E-mail',
  currency: 'Moeda',
  amount: 'Valor',
  gmv: 'GMV',
  net_gmv: 'GMV líquido',
  refunded_gmv: 'Devoluções',
  orders: 'Pedidos',
  attributed_orders: 'Pedidos atribuídos',
  active_creators: 'Creators ativos',
  selected_creators: 'Creators selecionados',
  approved_posts: 'Conteúdos aprovados',
  commission_pending: 'Comissão pendente',
  commission_available: 'Saldo disponível',
  commission_reserved: 'Saldo reservado',
  commission_paid: 'Comissão paga',
  net_commission: 'Comissão líquida',
  commission_accrued: 'Comissão acumulada',
  commission_adjustments: 'Ajustes de comissão',
  pending: 'Pendente',
  available: 'Disponível',
  reserved: 'Reservado',
  paid: 'Pago',
  draft: 'Rascunho',
  active: 'Ativo',
  paused: 'Pausado',
  archived: 'Arquivado',
  submitted: 'Enviada',
  in_review: 'Em análise',
  approved: 'Aprovado',
  rejected: 'Rejeitado',
  withdrawn: 'Retirada',
  awaiting_terms: 'Aguardando termos',
  offboarded: 'Encerrado',
  selected: 'Selecionado',
  removed: 'Removido',
  detected: 'Detectado',
  matched: 'Identificado',
  confirmed: 'Confirmado',
  failed: 'Falhou',
  unknown: 'Resultado desconhecido',
  cancelled: 'Cancelado',
  canceled: 'Cancelado',
  queued: 'Na fila',
  running: 'Em andamento',
  completed: 'Concluído',
  open: 'Aberto',
  resolved: 'Resolvido',
  dismissed: 'Encerrado manualmente',
  gated: 'Validado',
  blocked: 'Bloqueado',
  stale: 'Desatualizado',
  executed: 'Executado',
  passed: 'Aprovado',
  expired: 'Expirado',
  revoked: 'Revogado',
  accepted: 'Aceito',
  used: 'Utilizado',
  coupon: 'Cupom',
  last_click: 'Clique',
  unattributed: 'Sem atribuição',
  external_id: 'Pedido externo',
  gross_amount: 'Valor bruto',
  refunded_amount: 'Valor devolvido',
  paid_at: 'Pago em',
  reason: 'Motivo',
  signals: 'Sinais da atribuição',
  attribution: 'Atribuição',
  commissions: 'Comissões',
  plan_id: 'Plano',
  plan_version: 'Versão do plano',
  gross_basis: 'Base bruta',
  rate: 'Taxa',
  base_rate: 'Taxa base',
  kind: 'Tipo',
  period_key: 'Período',
  eligible_at: 'Elegível em',
  available_at: 'Disponível em',
  bucket: 'Bucket',
  entry_type: 'Lançamento',
  description: 'Descrição',
  reviewed_by: 'Revisado por',
  reviewed_at: 'Revisado em',
  metrics: 'Métricas',
  social_metrics: 'Métricas sociais',
  network: 'Rede',
  handle: 'Handle',
  handle_normalized: 'Handle normalizado',
  published_at: 'Publicado em',
  external_post_id: 'ID externo',
  version: 'Versão',
  required_terms: 'Termos vigentes',
  accepted_terms_version: 'Versão aceita',
  balance: 'Saldo',
  assets: 'Assets',
  creator: 'Creator',
  socials: 'Perfis sociais',
  verified: 'Verificado',
  asset_type: 'Tipo de asset',
  code: 'Código',
  target_url: 'Destino',
  terms_id: 'Versão dos termos',
  content: 'Conteúdo',
  required: 'Obrigatório',
  briefing: 'Briefing',
  starts_at: 'Início',
  ends_at: 'Fim',
  attribution_window_days: 'Janela de atribuição (dias)',
  return_window_days: 'Janela de devolução (dias)',
  payout_minimum: 'Mínimo para pagamento',
  active_from: 'Vigência',
  tiers: 'Faixas',
  bonuses: 'Bônus',
  threshold_gmv: 'Limite de GMV',
  threshold: 'Meta',
  metric: 'Métrica',
  motivation: 'Motivação',
  review_note: 'Nota da revisão',
  note: 'Observação',
  comment: 'Comentário',
  decision: 'Decisão',
  expires_at: 'Expira em',
  expires_in_hours: 'Validade (horas)',
  cutoff_at: 'Data de corte',
  scenario: 'Cenário do simulador',
  payouts: 'Pagamentos',
  batch: 'Lote',
  batch_id: 'Lote',
  created_by: 'Criado por',
  approved_by: 'Aprovado por',
  provider_reference: 'Referência do provedor',
  run_id: 'Reconciliação',
  payout_id: 'Pagamento',
  finding_id: 'Finding',
  finding_type: 'Tipo de divergência',
  evidence: 'Evidências',
  evidence_hash: 'Hash da evidência',
  payout_version: 'Versão do payout',
  action: 'Ação',
  rationale: 'Justificativa',
  risk: 'Risco',
  proposed_changes: 'Alterações propostas',
  gates: 'Validações',
  checks: 'Verificações',
  result: 'Resultado',
  approval_comment: 'Comentário da aprovação',
  approved_at: 'Aprovado em',
  rejection_comment: 'Comentário da rejeição',
  rejected_by: 'Rejeitado por',
  rejected_at: 'Rejeitado em',
  executed_at: 'Executado em',
  started_at: 'Início',
  started_by: 'Iniciado por',
  completed_at: 'Concluído em',
  summary: 'Resumo',
  actor_user_id: 'Ator',
  entity_type: 'Tipo de entidade',
  entity_id: 'Entidade',
  data: 'Dados',
  from_at: 'De',
  to_at: 'Até',
  as_of: 'Liquidar até',
  posts: 'Posts',
  caption: 'Legenda',
  url: 'URL',
  membership_ids: 'Parcerias',
  password: 'Senha',
  brand_slug: 'Marca',
  slug: 'Slug',
  source: 'Origem',
  activated_at: 'Ativado em',
  used_at: 'Utilizado em',
  revoked_at: 'Revogado em',
  selected_at: 'Selecionado em',
  selected_by: 'Selecionado por',
  removed_at: 'Removido em',
  resolved_at: 'Resolvido em',
  confirm_payout: 'Confirmar pagamento',
  mark_failed_release: 'Marcar falha e liberar reserva',
  manual_review: 'Revisão manual',
};
export function label(key: string) {
  return labels[key] ?? key.replaceAll('_', ' ');
}
export const financialFields = new Set([
  'amount',
  'gmv',
  'net_gmv',
  'refunded_gmv',
  'gross_amount',
  'refunded_amount',
  'gross_basis',
  'payout_minimum',
  'threshold_gmv',
  'commission_pending',
  'commission_available',
  'commission_reserved',
  'commission_paid',
  'commission_accrued',
  'commission_adjustments',
  'net_commission',
  'pending',
  'available',
  'reserved',
  'paid',
]);

Object.assign(labels, {
  closed: 'Encerrado',
  scheduled: 'Agendado',
  ended: 'Finalizado',
  created: 'Criado',
  partially_refunded: 'Parcialmente devolvido',
  refunded: 'Devolvido',
  partially_failed: 'Falha parcial',
  processing: 'Processando',
  proposed: 'Com proposta',
  reversed: 'Revertido',
  sale: 'Venda',
  bonus: 'Bônus',
  refund_adjustment: 'Ajuste de devolução',
  evidence_hash: 'Hash da evidência',
  finding_open: 'Divergência em aberto',
  payout_version: 'Versão do pagamento',
  tenant_scope: 'Escopo da marca',
  current_state: 'Estado atual',
  reserved_balance: 'Reserva integral',
  provider_confirmation: 'Confirmação do provedor',
  no_duplicate_financial_effect: 'Ausência de efeito duplicado',
  provider_absence: 'Ausência de transferência',
  executable_action: 'Ação executável',
  commission_accrued: 'Comissão acumulada',
  commission_settled: 'Comissão liquidada',
  commission_reversed: 'Comissão revertida',
  payout_reserved: 'Reserva para pagamento',
  payout_confirmed: 'Pagamento confirmado',
  payout_released: 'Reserva liberada',
  reconciliation_adjustment: 'Ajuste de reconciliação',
  provider_confirmed_internal_unknown: 'Provedor confirmou; resultado interno desconhecido',
  provider_missing_internal_unknown: 'Sem transferência no provedor',
  amount_mismatch: 'Divergência de valor',
  duplicate_provider_transfer: 'Transferência duplicada',
  ledger_balance_mismatch: 'Divergência no saldo',
  idempotency_key: 'Chave idempotente',
  proposal_id: 'Proposta',
  detail: 'Detalhe',
});
